# Generated by Django 3.1.1 on 2020-09-29 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200929_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
