# Generated by Django 3.1.1 on 2020-09-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200929_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('PLA', 'plants and seeds'), ('CMP', 'plant food and friends'), ('ACC', 'tools and accessories'), ('HMD', 'Handmade plant art'), ('CNT', 'pots, vases and jars')], default='PLA', max_length=3),
        ),
    ]
