# Generated by Django 3.1.1 on 2020-09-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='min_bid',
        ),
    ]
