# Generated by Django 3.1.2 on 2020-10-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_min_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('PLA', 'plants and seeds'), ('HMD', 'Handmade plant art'), ('CNT', 'pots, vases and jars')], default='PLA', max_length=3),
        ),
    ]
