# Generated by Django 3.1.1 on 2020-10-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201009_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
