# Generated by Django 3.1.1 on 2020-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201015_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default="{% static '/images/no_img.png' %}", max_length=500, null=True),
        ),
    ]
