# Generated by Django 3.1.1 on 2020-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201016_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
