# Generated by Django 3.1.1 on 2020-10-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_user_last_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_visit',
        ),
    ]
