# Generated by Django 3.1.1 on 2020-10-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_user_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('PLA', 'plants and seeds'), ('HMD', 'Handmade plant art'), ('CNT', 'pots, vases and jars')], default='PLA', max_length=4),
        ),
    ]
